/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BuyMyRoom__factory } from "./BuyMyRoom__factory";
export { MyERC20__factory } from "./MyERC20__factory";
